name: tbn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - tqdm
  - pillow
  - scikit-learn
  - einops
  - matplotlib
  - tensorboardX
  - pytorch
  - torchvision
  - pip
  - pyyaml
  - pip:
      - pyts
